name: Run pre-commit hooks on PRs
on: [pull_request]

jobs:
  run:
    name: Run pre-commit action
    runs-on: ubuntu-latest
    steps: 
#    - name: Checkout repository
#      uses: actions/checkout@master
#
    - name: Run pre-commit
      uses: ./.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
